stages:
  - test
  - build

services:
  - docker:dind

test:
  stage: test
  image: maven:3.6.1-jdk-11-slim
  script:
    - mvn test
    - mvn jacoco:report
    - cat target/site/jacoco/index.html
    - ./sonar.sh