stages:
  - test
  - analyze
  - build

services:
  - docker:dind

test:
  stage: test
  image: maven:3.6.0-jdk-8-alpine
  artifacts:
    paths:
      - target/*
  script:
    - mvn package
    - mvn test

analyze:
  stage: analyze
  image: maven:3.6.0-jdk-8-alpine
  artifacts:
    paths:
      - target/*
  script:
    - mvn package
    - ./sonar.sh

build:
  stage: build
  image: docker:stable
  script:
    - apk update
    - apk add curl
    - apk add git
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
    - ./build.sh
    - ./push.sh
    - curl -X POST https://hooks.microbadger.com/images/uniqe15/event-sourced-bank/qAYbnGd4JHMW8TYFCtdrx8OBySM=
  only:
    - master