stages:
  - test
  - analyze
  - build

services:
  - docker:dind

test:
  stage: test
  image: maven:3.6.0-jdk-8-alpine
  artifacts:
    paths:
      - target/*
  script:
    - mvn package
    - mvn test

analyze:
  stage: analyze
  image: maven:3.6.0-jdk-8-alpine
  artifacts:
    paths:
      - target/*
  script:
    - mvn package
    - ./sonar.sh

build:
  stage: build
  image: docker:stable
  script:
    - docker info
    - docker login registry.gitlab.com -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - ./build.sh
    - ./push.sh
  only:
    - master