apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bankapp
spec:
  selector:
    matchLabels:
      app: bank
  serviceName: bank
  replicas: 1
  template:
    metadata:
      labels:
        app: bank
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: bank
          image: uniqe15/event-sourced-bank
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: bank
  labels:
    app: bank
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: bank
  clusterIP: None
  selector:
    app: bank